/**
 * Inserts deterministic demo data for local testing (workouts, nutrition, vitals).
 * If SEED_USER_EMAIL already exists, that account is reused (not deleted or recreated).
 * Re-running replaces only rows produced by this script (same template name, meal days, vital keys/days).
 *
 * Usage: `npm run db:seed`
 * Env: DATABASE_URL (optional, defaults to file:./data/local.db), SEED_USER_EMAIL, SEED_USER_PASSWORD (new users only)
 * Loads `.env` and `.env.local` from the project root (same idea as Next.js).
 */

import "./load-env";

import { and, eq, inArray, or } from "drizzle-orm";

import { db } from "@/db/client";
import {
  mealEntries,
  meals,
  userProfiles,
  userVitalEntries,
  users,
  workoutSessions,
  workoutSets,
  workoutTemplateItems,
  workoutTemplates,
} from "@/db/schema";
import { addDaysKey, formatDayKey, parseDayKey } from "@/lib/date-key";
import { hashPassword } from "@/lib/password";
import { ensurePresetExercisesSeeded } from "@/lib/services/workouts";

const SEED_EMAIL = process.env.SEED_USER_EMAIL ?? "seed@test.local";
const SEED_PASSWORD = process.env.SEED_USER_PASSWORD ?? "password";
const SEED_NAME = process.env.SEED_USER_NAME ?? "Seed User";

const TEMPLATE_NAME = "Seed — Push + legs";

const EX_BENCH = "pre00000001";
const EX_SQUAT = "pre00000040";
const EX_ROW = "pre00000012";

function localDateAtHour(dayKey: string, hour: number, minute = 0) {
  const d = parseDayKey(dayKey);
  if (!d) throw new Error(`Invalid dayKey: ${dayKey}`);
  d.setHours(hour, minute, 0, 0);
  return d;
}

async function removePreviousSeedWorkouts(userId: string) {
  const tpls = await db.query.workoutTemplates.findMany({
    where: and(
      eq(workoutTemplates.userId, userId),
      eq(workoutTemplates.name, TEMPLATE_NAME)
    ),
    columns: { id: true },
  });
  for (const t of tpls) {
    const sessRows = await db
      .select({ id: workoutSessions.id })
      .from(workoutSessions)
      .where(eq(workoutSessions.templateId, t.id));
    const sessionIds = sessRows.map((r) => r.id);
    if (sessionIds.length > 0) {
      await db
        .delete(workoutSets)
        .where(inArray(workoutSets.sessionId, sessionIds));
    }
    await db
      .delete(workoutSessions)
      .where(eq(workoutSessions.templateId, t.id));
    await db
      .delete(workoutTemplateItems)
      .where(eq(workoutTemplateItems.templateId, t.id));
    await db.delete(workoutTemplates).where(eq(workoutTemplates.id, t.id));
  }
}

async function removePreviousSeedMeals(userId: string, dayKeys: string[]) {
  if (dayKeys.length === 0) return;
  await db
    .delete(meals)
    .where(and(eq(meals.userId, userId), inArray(meals.dayKey, dayKeys)));
}

async function removePreviousSeedVitals(
  userId: string,
  weightDayKeys: string[],
  restingDayKey: string
) {
  await db.delete(userVitalEntries).where(
    and(
      eq(userVitalEntries.userId, userId),
      or(
        and(
          eq(userVitalEntries.vitalKey, "body_weight_lb"),
          inArray(userVitalEntries.dayKey, weightDayKeys)
        ),
        and(
          eq(userVitalEntries.vitalKey, "resting_hr"),
          eq(userVitalEntries.dayKey, restingDayKey)
        )
      )
    )
  );
  await db.delete(userVitalEntries).where(
    and(
      eq(userVitalEntries.userId, userId),
      eq(userVitalEntries.vitalKey, "height_in")
    )
  );
}

async function main() {
  console.log("Seeding database…");

  const existing = await db.query.users.findFirst({
    where: eq(users.email, SEED_EMAIL),
  });

  let userId: string;
  if (existing) {
    userId = existing.id;
    console.log(`Using existing user ${SEED_EMAIL} (skipped account creation).`);
  } else {
    userId = crypto.randomUUID();
    await db.insert(users).values({
      id: userId,
      name: SEED_NAME,
      email: SEED_EMAIL,
      passwordHash: await hashPassword(SEED_PASSWORD),
    });
    console.log(`Created user ${SEED_EMAIL} (password: ${SEED_PASSWORD})`);
  }

  const today = formatDayKey();
  const mealDays = Array.from({ length: 14 }, (_, i) => addDaysKey(today, -i));
  const weightDayKeys = Array.from({ length: 40 }, (_, i) => addDaysKey(today, -i));

  await ensurePresetExercisesSeeded();
  await removePreviousSeedWorkouts(userId);
  await removePreviousSeedMeals(userId, mealDays);
  await removePreviousSeedVitals(userId, weightDayKeys, today);

  const templateId = crypto.randomUUID();
  await db.insert(workoutTemplates).values({
    id: templateId,
    userId,
    name: TEMPLATE_NAME,
    notes: "Generated by db:seed",
  });

  await db.insert(workoutTemplateItems).values([
    {
      id: crypto.randomUUID(),
      templateId,
      exerciseId: EX_BENCH,
      order: 0,
      targetSets: 3,
      targetReps: 5,
      defaultWeight: 135,
      weightUnit: "lb",
      progressiveOverloadEnabled: false,
    },
    {
      id: crypto.randomUUID(),
      templateId,
      exerciseId: EX_SQUAT,
      order: 1,
      targetSets: 3,
      targetReps: 5,
      defaultWeight: 185,
      weightUnit: "lb",
      progressiveOverloadEnabled: false,
    },
    {
      id: crypto.randomUUID(),
      templateId,
      exerciseId: EX_ROW,
      order: 2,
      targetSets: 3,
      targetReps: 8,
      defaultWeight: 95,
      weightUnit: "lb",
      progressiveOverloadEnabled: false,
    },
  ]);

  /** Every ~3 days for the last ~3 weeks */
  const sessionDayKeys = [3, 6, 9, 12, 15, 18, 21].map((d) =>
    addDaysKey(today, -d)
  );

  for (let si = 0; si < sessionDayKeys.length; si++) {
    const dayKey = sessionDayKeys[si]!;
    const startedAt = localDateAtHour(dayKey, 9, 30);
    const endedAt = new Date(startedAt.getTime() + 42 * 60 * 1000);
    const sessionId = crypto.randomUUID();

    const bench = 115 + si * 5;
    const squat = 165 + si * 7.5;
    const row = 85 + si * 2.5;

    await db.insert(workoutSessions).values({
      id: sessionId,
      userId,
      templateId,
      startedAt,
      endedAt,
      status: "completed",
    });

    const exercisesCfg = [
      { exerciseId: EX_BENCH, weight: bench, reps: 5 },
      { exerciseId: EX_SQUAT, weight: squat, reps: 5 },
      { exerciseId: EX_ROW, weight: row, reps: 8 },
    ] as const;

    for (const ex of exercisesCfg) {
      for (let setIndex = 1; setIndex <= 3; setIndex++) {
        await db.insert(workoutSets).values({
          id: crypto.randomUUID(),
          sessionId,
          exerciseId: ex.exerciseId,
          setIndex,
          reps: ex.reps,
          weight: ex.weight,
        });
      }
    }
  }
  console.log(`Inserted ${sessionDayKeys.length} completed workout sessions.`);

  for (const dayKey of mealDays) {
    const breakfastId = crypto.randomUUID();
    const lunchId = crypto.randomUUID();
    await db.insert(meals).values([
      {
        id: breakfastId,
        userId,
        dayKey,
        loggedAt: localDateAtHour(dayKey, 8, 15),
        name: "Breakfast",
      },
      {
        id: lunchId,
        userId,
        dayKey,
        loggedAt: localDateAtHour(dayKey, 12, 0),
        name: "Lunch",
      },
    ]);
    await db.insert(mealEntries).values([
      {
        id: crypto.randomUUID(),
        mealId: breakfastId,
        description: "Oats + eggs",
        calories: 520,
        proteinG: 32,
        carbsG: 48,
        fatG: 18,
      },
      {
        id: crypto.randomUUID(),
        mealId: lunchId,
        description: "Chicken bowl",
        calories: 680,
        proteinG: 48,
        carbsG: 62,
        fatG: 22,
      },
    ]);
  }
  console.log(`Inserted meals for ${mealDays.length} days.`);

  await db
    .insert(userProfiles)
    .values({
      userId,
      heightIn: 70,
      goalPreset: "build_strength",
      fitnessGoals: "Stay consistent with 3× weekly training.",
      preferences:
        "Home gym: barbell, bench, dumbbells. Enjoys high-protein meals.",
    })
    .onConflictDoUpdate({
      target: userProfiles.userId,
      set: {
        heightIn: 70,
        goalPreset: "build_strength",
        fitnessGoals: "Stay consistent with 3× weekly training.",
        preferences:
          "Home gym: barbell, bench, dumbbells. Enjoys high-protein meals.",
      },
    });

  for (let i = 0; i < 40; i++) {
    const dayKey = addDaysKey(today, -i);
    const w = 192 - i * 0.15;
    await db.insert(userVitalEntries).values({
      id: crypto.randomUUID(),
      userId,
      vitalKey: "body_weight_lb",
      dayKey,
      value: Math.round(w * 10) / 10,
      recordedAt: localDateAtHour(dayKey, 7, 30),
    });
  }

  await db.insert(userVitalEntries).values({
    id: crypto.randomUUID(),
    userId,
    vitalKey: "resting_hr",
    dayKey: today,
    value: 58,
    recordedAt: localDateAtHour(today, 8, 0),
  });

  console.log("Inserted vitals (weight trend, resting HR) and profile height.");
  console.log("Done.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
