/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppWorkoutsRouteRouteImport } from './routes/app/workouts/route'
import { Route as AppNutritionRouteRouteImport } from './routes/app/nutrition/route'
import { Route as AppCoachRouteRouteImport } from './routes/app/coach/route'
import { Route as AppWorkoutsIndexRouteImport } from './routes/app/workouts/index'
import { Route as AppNutritionIndexRouteImport } from './routes/app/nutrition/index'
import { Route as AppCoachIndexRouteImport } from './routes/app/coach/index'
import { Route as AppWorkoutsCalendarRouteImport } from './routes/app/workouts/calendar'
import { Route as AppWorkoutsIdRouteImport } from './routes/app/workouts/$id'
import { Route as AppNutritionPlanRouteImport } from './routes/app/nutrition/plan'
import { Route as AppNutritionLibraryRouteImport } from './routes/app/nutrition/library'
import { Route as AppCoachIdRouteImport } from './routes/app/coach/$id'
import { Route as ApiSyncCollectionRouteImport } from './routes/api/sync/$collection'
import { Route as ApiCoachChatRouteImport } from './routes/api/coach/chat'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthDeviceTokensRouteImport } from './routes/api/auth/device-tokens'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppWorkoutsSessionSessionIdRouteImport } from './routes/app/workouts/session.$sessionId'
import { Route as ApiNutritionMealPlanShoppingListRouteImport } from './routes/api/nutrition/meal-plan/shopping-list'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutsRouteRoute = AppWorkoutsRouteRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNutritionRouteRoute = AppNutritionRouteRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoachRouteRoute = AppCoachRouteRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutsIndexRoute = AppWorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkoutsRouteRoute,
} as any)
const AppNutritionIndexRoute = AppNutritionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNutritionRouteRoute,
} as any)
const AppCoachIndexRoute = AppCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoachRouteRoute,
} as any)
const AppWorkoutsCalendarRoute = AppWorkoutsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppWorkoutsRouteRoute,
} as any)
const AppWorkoutsIdRoute = AppWorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkoutsRouteRoute,
} as any)
const AppNutritionPlanRoute = AppNutritionPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppNutritionRouteRoute,
} as any)
const AppNutritionLibraryRoute = AppNutritionLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppNutritionRouteRoute,
} as any)
const AppCoachIdRoute = AppCoachIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCoachRouteRoute,
} as any)
const ApiSyncCollectionRoute = ApiSyncCollectionRouteImport.update({
  id: '/api/sync/$collection',
  path: '/api/sync/$collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachChatRoute = ApiCoachChatRouteImport.update({
  id: '/api/coach/chat',
  path: '/api/coach/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDeviceTokensRoute = ApiAuthDeviceTokensRouteImport.update({
  id: '/api/auth/device-tokens',
  path: '/api/auth/device-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutsSessionSessionIdRoute =
  AppWorkoutsSessionSessionIdRouteImport.update({
    id: '/session/$sessionId',
    path: '/session/$sessionId',
    getParentRoute: () => AppWorkoutsRouteRoute,
  } as any)
const ApiNutritionMealPlanShoppingListRoute =
  ApiNutritionMealPlanShoppingListRouteImport.update({
    id: '/api/nutrition/meal-plan/shopping-list',
    path: '/api/nutrition/meal-plan/shopping-list',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/coach': typeof AppCoachRouteRouteWithChildren
  '/app/nutrition': typeof AppNutritionRouteRouteWithChildren
  '/app/workouts': typeof AppWorkoutsRouteRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/device-tokens': typeof ApiAuthDeviceTokensRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/coach/chat': typeof ApiCoachChatRoute
  '/api/sync/$collection': typeof ApiSyncCollectionRoute
  '/app/coach/$id': typeof AppCoachIdRoute
  '/app/nutrition/library': typeof AppNutritionLibraryRoute
  '/app/nutrition/plan': typeof AppNutritionPlanRoute
  '/app/workouts/$id': typeof AppWorkoutsIdRoute
  '/app/workouts/calendar': typeof AppWorkoutsCalendarRoute
  '/app/coach/': typeof AppCoachIndexRoute
  '/app/nutrition/': typeof AppNutritionIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
  '/api/nutrition/meal-plan/shopping-list': typeof ApiNutritionMealPlanShoppingListRoute
  '/app/workouts/session/$sessionId': typeof AppWorkoutsSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/device-tokens': typeof ApiAuthDeviceTokensRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/coach/chat': typeof ApiCoachChatRoute
  '/api/sync/$collection': typeof ApiSyncCollectionRoute
  '/app/coach/$id': typeof AppCoachIdRoute
  '/app/nutrition/library': typeof AppNutritionLibraryRoute
  '/app/nutrition/plan': typeof AppNutritionPlanRoute
  '/app/workouts/$id': typeof AppWorkoutsIdRoute
  '/app/workouts/calendar': typeof AppWorkoutsCalendarRoute
  '/app/coach': typeof AppCoachIndexRoute
  '/app/nutrition': typeof AppNutritionIndexRoute
  '/app/workouts': typeof AppWorkoutsIndexRoute
  '/api/nutrition/meal-plan/shopping-list': typeof ApiNutritionMealPlanShoppingListRoute
  '/app/workouts/session/$sessionId': typeof AppWorkoutsSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/coach': typeof AppCoachRouteRouteWithChildren
  '/app/nutrition': typeof AppNutritionRouteRouteWithChildren
  '/app/workouts': typeof AppWorkoutsRouteRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/device-tokens': typeof ApiAuthDeviceTokensRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/coach/chat': typeof ApiCoachChatRoute
  '/api/sync/$collection': typeof ApiSyncCollectionRoute
  '/app/coach/$id': typeof AppCoachIdRoute
  '/app/nutrition/library': typeof AppNutritionLibraryRoute
  '/app/nutrition/plan': typeof AppNutritionPlanRoute
  '/app/workouts/$id': typeof AppWorkoutsIdRoute
  '/app/workouts/calendar': typeof AppWorkoutsCalendarRoute
  '/app/coach/': typeof AppCoachIndexRoute
  '/app/nutrition/': typeof AppNutritionIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
  '/api/nutrition/meal-plan/shopping-list': typeof ApiNutritionMealPlanShoppingListRoute
  '/app/workouts/session/$sessionId': typeof AppWorkoutsSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/coach'
    | '/app/nutrition'
    | '/app/workouts'
    | '/app/calendar'
    | '/app/profile'
    | '/app/progress'
    | '/app/'
    | '/api/auth/$'
    | '/api/auth/device-tokens'
    | '/api/auth/refresh'
    | '/api/coach/chat'
    | '/api/sync/$collection'
    | '/app/coach/$id'
    | '/app/nutrition/library'
    | '/app/nutrition/plan'
    | '/app/workouts/$id'
    | '/app/workouts/calendar'
    | '/app/coach/'
    | '/app/nutrition/'
    | '/app/workouts/'
    | '/api/nutrition/meal-plan/shopping-list'
    | '/app/workouts/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/calendar'
    | '/app/profile'
    | '/app/progress'
    | '/app'
    | '/api/auth/$'
    | '/api/auth/device-tokens'
    | '/api/auth/refresh'
    | '/api/coach/chat'
    | '/api/sync/$collection'
    | '/app/coach/$id'
    | '/app/nutrition/library'
    | '/app/nutrition/plan'
    | '/app/workouts/$id'
    | '/app/workouts/calendar'
    | '/app/coach'
    | '/app/nutrition'
    | '/app/workouts'
    | '/api/nutrition/meal-plan/shopping-list'
    | '/app/workouts/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/coach'
    | '/app/nutrition'
    | '/app/workouts'
    | '/app/calendar'
    | '/app/profile'
    | '/app/progress'
    | '/app/'
    | '/api/auth/$'
    | '/api/auth/device-tokens'
    | '/api/auth/refresh'
    | '/api/coach/chat'
    | '/api/sync/$collection'
    | '/app/coach/$id'
    | '/app/nutrition/library'
    | '/app/nutrition/plan'
    | '/app/workouts/$id'
    | '/app/workouts/calendar'
    | '/app/coach/'
    | '/app/nutrition/'
    | '/app/workouts/'
    | '/api/nutrition/meal-plan/shopping-list'
    | '/app/workouts/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthDeviceTokensRoute: typeof ApiAuthDeviceTokensRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiCoachChatRoute: typeof ApiCoachChatRoute
  ApiSyncCollectionRoute: typeof ApiSyncCollectionRoute
  ApiNutritionMealPlanShoppingListRoute: typeof ApiNutritionMealPlanShoppingListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts': {
      id: '/app/workouts'
      path: '/workouts'
      fullPath: '/app/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/nutrition': {
      id: '/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AppNutritionRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts/': {
      id: '/app/workouts/'
      path: '/'
      fullPath: '/app/workouts/'
      preLoaderRoute: typeof AppWorkoutsIndexRouteImport
      parentRoute: typeof AppWorkoutsRouteRoute
    }
    '/app/nutrition/': {
      id: '/app/nutrition/'
      path: '/'
      fullPath: '/app/nutrition/'
      preLoaderRoute: typeof AppNutritionIndexRouteImport
      parentRoute: typeof AppNutritionRouteRoute
    }
    '/app/coach/': {
      id: '/app/coach/'
      path: '/'
      fullPath: '/app/coach/'
      preLoaderRoute: typeof AppCoachIndexRouteImport
      parentRoute: typeof AppCoachRouteRoute
    }
    '/app/workouts/calendar': {
      id: '/app/workouts/calendar'
      path: '/calendar'
      fullPath: '/app/workouts/calendar'
      preLoaderRoute: typeof AppWorkoutsCalendarRouteImport
      parentRoute: typeof AppWorkoutsRouteRoute
    }
    '/app/workouts/$id': {
      id: '/app/workouts/$id'
      path: '/$id'
      fullPath: '/app/workouts/$id'
      preLoaderRoute: typeof AppWorkoutsIdRouteImport
      parentRoute: typeof AppWorkoutsRouteRoute
    }
    '/app/nutrition/plan': {
      id: '/app/nutrition/plan'
      path: '/plan'
      fullPath: '/app/nutrition/plan'
      preLoaderRoute: typeof AppNutritionPlanRouteImport
      parentRoute: typeof AppNutritionRouteRoute
    }
    '/app/nutrition/library': {
      id: '/app/nutrition/library'
      path: '/library'
      fullPath: '/app/nutrition/library'
      preLoaderRoute: typeof AppNutritionLibraryRouteImport
      parentRoute: typeof AppNutritionRouteRoute
    }
    '/app/coach/$id': {
      id: '/app/coach/$id'
      path: '/$id'
      fullPath: '/app/coach/$id'
      preLoaderRoute: typeof AppCoachIdRouteImport
      parentRoute: typeof AppCoachRouteRoute
    }
    '/api/sync/$collection': {
      id: '/api/sync/$collection'
      path: '/api/sync/$collection'
      fullPath: '/api/sync/$collection'
      preLoaderRoute: typeof ApiSyncCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach/chat': {
      id: '/api/coach/chat'
      path: '/api/coach/chat'
      fullPath: '/api/coach/chat'
      preLoaderRoute: typeof ApiCoachChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/device-tokens': {
      id: '/api/auth/device-tokens'
      path: '/api/auth/device-tokens'
      fullPath: '/api/auth/device-tokens'
      preLoaderRoute: typeof ApiAuthDeviceTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workouts/session/$sessionId': {
      id: '/app/workouts/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/app/workouts/session/$sessionId'
      preLoaderRoute: typeof AppWorkoutsSessionSessionIdRouteImport
      parentRoute: typeof AppWorkoutsRouteRoute
    }
    '/api/nutrition/meal-plan/shopping-list': {
      id: '/api/nutrition/meal-plan/shopping-list'
      path: '/api/nutrition/meal-plan/shopping-list'
      fullPath: '/api/nutrition/meal-plan/shopping-list'
      preLoaderRoute: typeof ApiNutritionMealPlanShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCoachRouteRouteChildren {
  AppCoachIdRoute: typeof AppCoachIdRoute
  AppCoachIndexRoute: typeof AppCoachIndexRoute
}

const AppCoachRouteRouteChildren: AppCoachRouteRouteChildren = {
  AppCoachIdRoute: AppCoachIdRoute,
  AppCoachIndexRoute: AppCoachIndexRoute,
}

const AppCoachRouteRouteWithChildren = AppCoachRouteRoute._addFileChildren(
  AppCoachRouteRouteChildren,
)

interface AppNutritionRouteRouteChildren {
  AppNutritionLibraryRoute: typeof AppNutritionLibraryRoute
  AppNutritionPlanRoute: typeof AppNutritionPlanRoute
  AppNutritionIndexRoute: typeof AppNutritionIndexRoute
}

const AppNutritionRouteRouteChildren: AppNutritionRouteRouteChildren = {
  AppNutritionLibraryRoute: AppNutritionLibraryRoute,
  AppNutritionPlanRoute: AppNutritionPlanRoute,
  AppNutritionIndexRoute: AppNutritionIndexRoute,
}

const AppNutritionRouteRouteWithChildren =
  AppNutritionRouteRoute._addFileChildren(AppNutritionRouteRouteChildren)

interface AppWorkoutsRouteRouteChildren {
  AppWorkoutsIdRoute: typeof AppWorkoutsIdRoute
  AppWorkoutsCalendarRoute: typeof AppWorkoutsCalendarRoute
  AppWorkoutsIndexRoute: typeof AppWorkoutsIndexRoute
  AppWorkoutsSessionSessionIdRoute: typeof AppWorkoutsSessionSessionIdRoute
}

const AppWorkoutsRouteRouteChildren: AppWorkoutsRouteRouteChildren = {
  AppWorkoutsIdRoute: AppWorkoutsIdRoute,
  AppWorkoutsCalendarRoute: AppWorkoutsCalendarRoute,
  AppWorkoutsIndexRoute: AppWorkoutsIndexRoute,
  AppWorkoutsSessionSessionIdRoute: AppWorkoutsSessionSessionIdRoute,
}

const AppWorkoutsRouteRouteWithChildren =
  AppWorkoutsRouteRoute._addFileChildren(AppWorkoutsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppCoachRouteRoute: typeof AppCoachRouteRouteWithChildren
  AppNutritionRouteRoute: typeof AppNutritionRouteRouteWithChildren
  AppWorkoutsRouteRoute: typeof AppWorkoutsRouteRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCoachRouteRoute: AppCoachRouteRouteWithChildren,
  AppNutritionRouteRoute: AppNutritionRouteRouteWithChildren,
  AppWorkoutsRouteRoute: AppWorkoutsRouteRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthDeviceTokensRoute: ApiAuthDeviceTokensRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiCoachChatRoute: ApiCoachChatRoute,
  ApiSyncCollectionRoute: ApiSyncCollectionRoute,
  ApiNutritionMealPlanShoppingListRoute: ApiNutritionMealPlanShoppingListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
